### ISSUE TITLE
Improve interop by giving users access via `into_iter` and maybe `iter` instead of `compile`

### ISSUE THREAD

**Issue by epage** [Freyskeyd/environment#7]
The current approach should work with `inter_iter`.  `iter` would require moving the inheritance logic into the `fn inherit`.

This also ensures the data structure used for implementation isn't exposed.

**Comment by Freyskeyd** [comment]
@epage 

I think it will be complicated. Because Environment implement `From<T>` which is used to do thing like: `[("FOO", "BAR")].into()` to create an Environment object.

It will be a conflict implementation I think. If you have any suggestion I'm fully aware :)

**Comment by epage** [comment]
I'm confused.  Why would implementing the `InterIterator` trait and adding a `fn iter` to your `impl` conflict with `From`?  `HashMap` has similar collection of trait and fn's.

**Comment by Freyskeyd** [comment]
What do you call `InterIterator`?

**Comment by epage** [comment]
Bah, I keep repeating a type for `IntoInterator`

**Comment by Freyskeyd** [comment]
fix by #10
